---
samba_domain: ADDS.STARSYSTEM.DEV
samba_workgroup: STARSYSTEM

samba_ntp_server: dc1.adds.starsystem.dev

samba_admin_user: Administrator
samba_organizational_unit: Constellation/File Servers

samba_homedir_template: /home/%U
samba_shell_template: /sbin/nologin
samba_shares:
  - name: homes
    comment: User storage
    path: /shares/users/%U
    valid_users: "@Storage Users"
    browseable: no
    read_only: no
    create_mask: "0600"
    directory_mask: "0700"

  - name: Time Machine
    comment: Time Machine storage
    path: /shares/time-machine/%U
    valid_users: "@Time Machines"
    time_machine: yes
    browseable: no
    read_only: no
    create_mask: "0600"
    directory_mask: "0700"

  - name: Media
    comment: Shared media files
    path: /shares/media
    valid_users: "@Media Managers"
    browseable: yes
    read_only: no
    create_mask: "0660"
    directory_mask: "0770"