[global]
    # --- Logging
    log file = /var/log/samba/log.%m
    logging = file
    max log size = 1000
    panic action = /usr/share/samba/panic-action %d

    # --- Active Directory
    # NetBIOS name (no .TLD)
    workgroup = STARSYSTEM
    # Full Kerberos realm (uppercase)
    realm = ADDS.STARSYSTEM.DEV
    # Use Active Directory for auth
    security = ADS
    # Allow 'username' not 'STARSYSTEM\username'
    winbind use default domain = yes
    # Don't cache credentials offline
    winbind offline logon = no

    # --- User defaults
    # Shell for AD users on Linux
    template shell = /sbin/nologin
    # Home dir template for AD users
    template homedir = /shares/users/%U

    # --- ID mapping between Unix and Windows
    # Simple consistent mapping (can also use autorid)
    idmap config * : backend = tdb
    # ID pool for non-STARSYSTEM objects
    idmap config * : range = 0-999999
    # Derive UID from Windows RID
    idmap config STARSYSTEM : backend = rid
    # Must not overlap * range
    idmap config STARSYSTEM : range = 1000000-1999999

    # --- macOS and Time Machine settings
    vfs objects = catia fruit streams_xattr
    fruit:metadata = stream
    fruit:posix_rename = yes
    fruit:veto_appledouble = no

[homes]
    comment = Personal network storage
    path = /shares/users/%U
    browseable = no
    read only = no
    create mask = 0600
    directory mask = 0700
    valid users = %S

[Time Machine]
    comment = Private share for macOS Time Machine
    path = /shares/time-machine/%U
    browseable = no
    read only = no
    create mask = 0700
    directory mask = 0700
    valid users = @"STARSYSTEM\\Time Machine"
    fruit:time machine = yes
    fruit:aapl = yes

[Media]
    comment = Shared media files
    path = /shares/media
    browseable = yes
    read only = no
    valid users = @"STARSYSTEM\\Media Managers"
    create mask = 0660
    directory mask = 0770