[homes]
    comment = User storage
    path = /home/%U
    valid users = "@Storage Users"
    browseable = no
    read only = no
    guest ok = no
    create mask = "0600"
    directory mask = "0700"

[Time Machine]
    comment = Time Machine storage
    path = /shares/time-machine/%U
    valid users = "@Time Machines"
    browseable = no
    read only = no
    guest ok = no
    create mask = "0600"
    directory mask = "0700"
    fruit:time machine = yes

[Media]
    comment = Shared media storage
    path = /shares/media
    valid users = "@Media Managers"
    browseable = yes
    read only = no
    guest ok = no
    create mask = "0660"
    directory mask = "0770"