[homes]
    comment = User storage
    path = /home/%U
    valid users = "@Storage Users"
    browseable = no
    read only = no
    guest ok = no
    create mask = "0600"
    directory mask = "0700"
    spotlight = no

[Media]
    comment = Shared media storage
    path = /shares/media
    valid users = "@Media Managers"
    browseable = yes
    read only = no
    guest ok = no
    create mask = "0660"
    directory mask = "0770"