[macmini]
    comment = Time Machine storage
    path = /shares/j.gledhill/macmini
    valid users = j.gledhill
    browseable = no
    read only = no
    guest ok = no
    create mask = "0600"
    directory mask = "0700"
    fruit:time machine = yes
    fruit:time machine max size = 1T
    spotlight = no
    smb encrypt = required