proxmox: PROXMOX {
  style: {
    stroke-dash: 3
  }

  constellationad: ACTIVE DIRECTORY
  samba: SAMBA
}

kubernetes: KUBERNETES {
  style: {
    stroke-dash: 3
  }

  authelia
}

user: USER {
  shape: person
}

user -> kubernetes.authelia: OIDC
kubernetes.authelia -> proxmox.constellationad: LDAP
user -> proxmox.samba: Kerberos
proxmox.samba -> proxmox.constellationad: Kerberos