---
galaxy_info:
  author: Jack-Gledhill
  description: Deploys a High-Availability k3s cluster to Raspberry Pis
  license: GPL-3.0
  min_ansible_version: 11.2.0
  galaxy_tags:
    - kubernetes
    - high-availability
    - k3s