---
- name: Install chrony for clock synchronisation
  ansible.builtin.apt:
    name: chrony
    state: present
    update_cache: true

- name: Enable chronyd
  ansible.builtin.systemd_service:
    name: chronyd
    state: enabled

- name: Copy chrony configuration
  ansible.builtin.template:
    src: chrony.conf
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart chronyd