---
- name: Install samba and winbind
  ansible.builtin.apt:
    name:
      - acl
      - attr
      - dnsutils
      - samba              # Implements SMB protocol
      - samba-common-tools # Provides CLI utilities like testparm
      - winbind            # Bridges Linux with AD
      - libpam-winbind     # Allows PAM to authenticate via winbind
      - libnss-winbind     # Allows NSS to look up AD users
    state: present
    update_cache: true

- name: Update samba configuration file
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0644'
    validate: testparm -s %s

- name: Enable pam_mkhomedir to create home directories on login
  ansible.builtin.command: pam-auth-update --enable mkhomedir

- name: Join the Active Directory forest
  ansible.builtin.command: net ads join -U {{ samba_admin_user }} createcomputer="{{ samba_organizational_unit }}"
  register: joined
  failed_when: joined.rc != 0
  notify: Restart winbind

- name: Enable samba services on boot
  ansible.builtin.systemd_service:
    name:
      - smbd
      - nmbd
      - winbindd
    state: enabled